import { useRef } from 'react';

import {
  useOrderPdfOverlayDraftEffects,
  useOrderPdfOverlayPdfRenderEffects,
  useOrderPdfOverlayShellEffects,
} from './order_pdf_overlay_controller_effects.js';
import {
  useOrderPdfOverlayEditorActions,
  useOrderPdfOverlayExportActions,
  useOrderPdfOverlayInteractionHandlers,
} from './order_pdf_overlay_controller_actions.js';
import type { OrderPdfOverlayControllerArgs } from './order_pdf_overlay_controller_shared.js';

export function useOrderPdfOverlayController(args: OrderPdfOverlayControllerArgs) {
  const { env, ui, refs, actions, apis } = args;
  const { app, fb, docMaybe, winMaybe, withV } = env;
  const {
    open,
    draftFromUi,
    zoomFromUi,
    draft,
    setDraft,
    zoom,
    setZoom,
    gmailBusy,
    setGmailBusy,
    imagePdfBusy,
    setImagePdfBusy,
    inlineConfirm,
    setInlineConfirm,
    dragOver,
    setDragOver,
    importedPdfImagePageCount,
    setImportedPdfImagePageCount,
    pdfPageReadyTick,
    setPdfPageReadyTick,
    pdfSourceTick,
    setPdfSourceTick,
  } = ui;
  const {
    canvasRef,
    detailsRichRef,
    notesRichRef,
    orderNoInputRef,
    containerRef,
    overlayRef,
    pdfFileInputRef,
    pdfJsRef,
    pdfBytesRef,
    pdfTemplateBytesRef,
    loadedPdfOriginalBytesRef,
    loadedPdfTailNonFormPageIndexesRef,
    pdfDocRef,
    pdfDocTaskRef,
    pageRef,
    pageSizeRef,
    pdfRenderTaskRef,
    pdfRenderQueueRef,
    pdfRenderReqIdRef,
    lastLoadedPdfTickRef,
    detailsDirtyRef,
    detailsUserIntentRef,
  } = refs;
  const { close, persistDraft, seedInitialDraft } = actions;
  const {
    runtimeApi,
    textApi,
    draftStateApi,
    pdfImportApi,
    interactionApi,
    pdfRenderApi,
    richEditorApi,
    exportFactoryApi,
    gmailApi,
    richProgrammaticApi,
  } = apis;

  const prevFocusRef = useRef<HTMLElement | null>(null);
  const didInitialFocusRef = useRef<boolean>(false);
  const autoRefreshAttemptedRef = useRef<boolean>(false);
  const openRef = useRef<boolean>(open);

  useOrderPdfOverlayDraftEffects({
    open,
    draftFromUi,
    draft,
    zoomFromUi,
    setDraft,
    setZoom,
    detailsDirtyRef,
    autoRefreshAttemptedRef,
    app,
    fb,
    runtimeApi,
    textApi,
    draftStateApi: {
      buildUntouchedDetailsRefreshDraft: draftStateApi.buildUntouchedDetailsRefreshDraft,
      createOrderPdfInitialDraft: draftStateApi.createOrderPdfInitialDraft,
      readOrderPdfDraftSeed: draftStateApi.readOrderPdfDraftSeed,
    },
    persistDraft,
    seedInitialDraft,
    close,
  });

  const exportActions = useOrderPdfOverlayExportActions({
    env: {
      app,
      fb,
      docMaybe,
      winMaybe,
      pdfJsRealWorkerUrl: env.pdfJsRealWorkerUrl,
    },
    draft,
    gmailBusy,
    imagePdfBusy,
    setGmailBusy,
    setImagePdfBusy,
    setImportedPdfImagePageCount,
    pdfSourceTick,
    setPdfSourceTick,
    pdfJsRef,
    pdfBytesRef,
    loadedPdfOriginalBytesRef,
    loadedPdfTailNonFormPageIndexesRef,
    persistDraft,
    pdfImportApi,
    pdfRenderApi: { ensureOrderPdfJs: pdfRenderApi.ensureOrderPdfJs },
    exportFactoryApi,
    gmailApi,
    runtimeApi: {
      canvasToPngBytes: runtimeApi.canvasToPngBytes,
      getFn: runtimeApi.getFn,
      getProp: runtimeApi.getProp,
      isPromiseLike: runtimeApi.isPromiseLike,
      isRecord: runtimeApi.isRecord,
      orderPdfOverlayReportNonFatal: runtimeApi.orderPdfOverlayReportNonFatal,
    },
  });

  const editorActions = useOrderPdfOverlayEditorActions({
    env: { app, fb, docMaybe },
    draft,
    setInlineConfirm,
    detailsRichRef,
    notesRichRef,
    detailsDirtyRef,
    detailsUserIntentRef,
    persistDraft,
    setZoom,
    inlineConfirm,
    draftStateApi,
    richEditorApi,
    richProgrammaticApi,
    runtimeApi: {
      clamp: runtimeApi.clamp,
      ensureExportApiReady: runtimeApi.ensureExportApiReady,
      getOrderPdfDraftFn: runtimeApi.getOrderPdfDraftFn,
      orderPdfOverlayReportNonFatal: runtimeApi.orderPdfOverlayReportNonFatal,
    },
  });

  const interactionHandlers = useOrderPdfOverlayInteractionHandlers({
    interactionApi,
    runtimeApi: { orderPdfOverlayReportNonFatal: runtimeApi.orderPdfOverlayReportNonFatal },
    fb,
    loadPdfIntoEditor: exportActions.loadPdfIntoEditor,
    close,
    dragOver,
    setDragOver,
    pdfFileInputRef,
  });

  useOrderPdfOverlayShellEffects({
    open,
    draft,
    docMaybe,
    winMaybe,
    detailsRichRef,
    notesRichRef,
    overlayRef,
    orderNoInputRef,
    prevFocusRef,
    didInitialFocusRef,
    detailsUserIntentRef,
    inlineConfirm,
    confirmInlineOk: editorActions.confirmInlineOk,
    confirmInlineCancel: editorActions.confirmInlineCancel,
    close,
    markRichProgrammatic: richProgrammaticApi.markRichProgrammatic,
    textApi: {
      safeStr: textApi.safeStr,
      textToHtml: textApi.textToHtml,
      htmlToTextPreserveNewlines: textApi.htmlToTextPreserveNewlines,
    },
    interactionApi: {
      installOrderPdfOverlayFocusTrap: interactionApi.installOrderPdfOverlayFocusTrap,
      installOrderPdfOverlayKeyboardGuards: interactionApi.installOrderPdfOverlayKeyboardGuards,
    },
    reportNonFatal: runtimeApi.orderPdfOverlayReportNonFatal,
  });

  useOrderPdfOverlayPdfRenderEffects({
    open,
    zoom,
    pdfPageReadyTick,
    pdfSourceTick,
    app,
    fb,
    withV,
    ensurePdfJs: exportActions.ensurePdfJs,
    setPdfPageReadyTick,
    setImportedPdfImagePageCount,
    setDragOver,
    canvasRef,
    containerRef,
    pdfTemplateBytesRef,
    pdfBytesRef,
    loadedPdfOriginalBytesRef,
    loadedPdfTailNonFormPageIndexesRef,
    pdfDocRef,
    pdfDocTaskRef,
    pageRef,
    pageSizeRef,
    pdfRenderTaskRef,
    pdfRenderQueueRef,
    pdfRenderReqIdRef,
    openRef,
    lastLoadedPdfTickRef,
    fetchFirstOk: runtimeApi.fetchFirstOk,
    pdfRenderApi,
    reportNonFatal: runtimeApi.orderPdfOverlayReportNonFatal,
  });

  return {
    detailsEditorHandlers: editorActions.detailsEditorHandlers,
    notesEditorHandlers: editorActions.notesEditorHandlers,
    handleScalarFieldChange: editorActions.handleScalarFieldChange,
    setZoomUi: editorActions.setZoomUi,
    refreshAuto: editorActions.refreshAuto,
    onLoadPdfClick: interactionHandlers.onLoadPdfClick,
    onPdfFileSelected: interactionHandlers.onPdfFileSelected,
    onStagePointerDownCapture: interactionHandlers.onStagePointerDownCapture,
    onStagePointerMoveCapture: interactionHandlers.onStagePointerMoveCapture,
    onStagePointerUpCapture: interactionHandlers.onStagePointerUpCapture,
    onStagePointerCancelCapture: interactionHandlers.onStagePointerCancelCapture,
    onStageDragOver: interactionHandlers.onStageDragOver,
    onStageDragLeave: interactionHandlers.onStageDragLeave,
    onStageDrop: interactionHandlers.onStageDrop,
    confirmInlineOk: editorActions.confirmInlineOk,
    confirmInlineCancel: editorActions.confirmInlineCancel,
    exportInteractive: exportActions.exportInteractive,
    exportImagePdf: exportActions.exportImagePdf,
    exportInteractiveToGmail: exportActions.exportInteractiveToGmail,
    exportInteractiveDownloadAndGmail: exportActions.exportInteractiveDownloadAndGmail,
    buildSketchPreview: exportActions.buildSketchPreview,
    onToggleRenderSketch: editorActions.onToggleRenderSketch,
    onToggleOpenClosed: editorActions.onToggleOpenClosed,
    appendSketchStroke: editorActions.appendSketchStroke,
    upsertSketchTextBox: editorActions.upsertSketchTextBox,
    deleteSketchTextBox: editorActions.deleteSketchTextBox,
    undoSketchStroke: editorActions.undoSketchStroke,
    redoSketchAnnotation: editorActions.redoSketchAnnotation,
    clearSketchStrokes: editorActions.clearSketchStrokes,
    importedPdfImagePageCount,
  };
}
