import type { ConfigStateLike, RemovedDoorsMap, UnknownRecord } from '../../../types/index.js';
import type { BaseLegColor, BaseLegStyle } from '../features/base_leg_support.js';

export type CornerBuildMeta = {
  stackKey?: 'top' | 'bottom';
  baseType?: unknown;
  baseLegStyle?: unknown;
  baseLegColor?: unknown;
  basePlinthHeightCm?: unknown;
  baseLegHeightCm?: unknown;
  baseLegWidthCm?: unknown;
  stackSplitEnabled?: boolean;
  stackOffsetZ?: number;
  [k: string]: unknown;
};

export type CornerBuildUI = UnknownRecord & {
  cornerConnectorEnabled?: boolean;
  cornerConnectorAsStandaloneCabinet?: boolean;
  cornerCabinetFrontPanel?: boolean;
  cornerCabinetOffsetXcm?: number;
  cornerCabinetOffsetZcm?: number;
  cornerCabinetWallLenCm?: number;
  cornerCabinetWallLen?: number;
  cornerConnectorWallLenCm?: number;
  cornerWidth?: number | string;
  cornerSide?: 'left' | 'right';
  cornerDoors?: number | string;
  cornerDoorCount?: number | string;
  cornerDoorsCount?: number | string;
  cornerHeight?: number | string;
  cornerHeightCm?: number | string;
  cornerDepth?: number | string;
  cornerDepthCm?: number | string;
  removeDoors?: boolean;
  removeDoorsEnabled?: boolean;
  corniceType?: string;
  baseType?: unknown;
  baseLegStyle?: unknown;
  baseLegColor?: unknown;
  basePlinthHeightCm?: unknown;
  baseLegHeightCm?: unknown;
  baseLegWidthCm?: unknown;
  layout?: unknown;
  doorStyle?: string;
  splitDoors?: boolean;
  groovesEnabled?: boolean;
  internalDrawersEnabled?: boolean;
  showHanger?: boolean;
  showContents?: boolean;
  hasCornice?: boolean;
};

export type CornerConfigRecord = UnknownRecord & {
  customData?: UnknownRecord & {
    shelves?: unknown[];
    rods?: unknown[];
    storage?: boolean;
  };
  intDrawersList?: unknown[];
  stackSplitLower?: UnknownRecord | null;
};

export type NormalizedCornerWingState = {
  uiAny: CornerBuildUI;
  __sketchMode: boolean;
  __stackKey: 'top' | 'bottom';
  __stackSplitEnabled: boolean;
  __stackOffsetZ: number;
  __mirrorX: 1 | -1;
  cornerSide: 'left' | 'right';
  cornerConnectorEnabled: boolean;
  wingLengthCM: number;
  wingW: number;
  wingH: number;
  wingD: number;
  blindWidth: number;
  activeWidth: number;
  activeFaceCenter: number;
  removeDoorsEnabled: boolean;
  doorStyle: string;
  splitDoors: boolean;
  groovesEnabled: boolean;
  internalDrawersEnabled: boolean;
  showHangerEnabled: boolean;
  showContentsEnabled: boolean;
  hasCorniceEnabled: boolean;
  __corniceAllowedForThisStack: boolean;
  __corniceTypeNorm: string;
  __cfg: ConfigStateLike;
  config: CornerConfigRecord;
  __removedDoorsMap: RemovedDoorsMap;
  __stackScopePartKey: (partId: unknown) => string;
  __isDoorRemoved: (partId: unknown) => boolean;
  baseType: string;
  baseLegStyle: BaseLegStyle;
  baseLegColor: BaseLegColor;
  basePlinthHeightCm: number;
  baseLegHeightCm: number;
  baseLegWidthCm: number;
  baseH: number;
  stackOffsetY: number;
  cabinetBodyHeight: number;
  cornerWallL: number;
  cornerOX: number;
  cornerOZ: number;
  roomCornerX: number;
  roomCornerZ: number;
  wingStartX: number;
  wingStartZ: number;
  wingRotationY: number;
  wingScaleX: number;
};
