import type { HingeMap, ProjectPreChestStateLike } from '../../../../../types';
import type { BaseLegColor, BaseLegStyle } from '../../../features/base_leg_support.js';
import type { StructurePattern } from './structure_tab_saved_models_patterns.js';

export type StructureTabViewState = {
  width: number;
  height: number;
  depth: number;
  doors: number;
  chestDrawersCount: number;
  baseType: 'plinth' | 'legs' | 'none';
  baseLegStyle: BaseLegStyle;
  baseLegColor: BaseLegColor;
  baseLegHeightCm: number;
  baseLegWidthCm: number;
  slidingTracksColor: 'nickel' | 'black';
  structureSelectRaw: string;
  singleDoorPosRaw: string;
  hingeDirection: boolean;
  cornerMode: boolean;
  cornerSide: 'left' | 'right';
  cornerWidth: number;
  cornerDoors: number;
  cornerHeight: number;
  cornerDepth: number;
  isChestMode: boolean;
  wardrobeType: 'hinged' | 'sliding';
  isManualWidth: boolean;
  preChestState: ProjectPreChestStateLike;
  isLibraryMode: boolean;
  libraryUpperDoorsHidden: boolean;
  hingeMap: HingeMap;
  primaryMode: string;
  hingeModeId: string;
  hingeEditActive: boolean;
  cellDimsModeId: string;
  cellDimsEditActive: boolean;
  stackSplitEnabled: boolean;
  stackSplitLowerHeight: number;
  stackSplitLowerDepthManual: boolean;
  stackSplitLowerWidthManual: boolean;
  stackSplitLowerDoorsManual: boolean;
  stackSplitLowerDepth: number;
  stackSplitLowerWidth: number;
  stackSplitLowerDoors: number;
  hasAnyCellDimsOverrides: boolean;
  modulesCount: number;
  defaultCellWidth: number;
  cellDimsWidth: number | '';
  cellDimsHeight: number | '';
  cellDimsDepth: number | '';
  patterns: StructurePattern[];
  structureSelect: string;
  structureIsDefault: boolean;
  structureArr: number[] | null;
  isSliding: boolean;
  shouldShowStructureButtons: boolean;
  shouldShowSingleDoor: boolean;
  shouldShowHingeBtn: boolean;
};
