// Grouped boot/history/render seams used by UI/platform bootstrap.

export { hasStoreReactivityInstalled } from './store_reactivity_access.js';

export {
  installStoreReactivityOrThrow,
  installStoreReactivityMaybe,
  canCommitBootSeedUiSnapshot,
  commitBootSeedUiSnapshotOrThrow,
  commitBootSeedUiSnapshotMaybe,
} from './store_boot_access.js';

export {
  getHistorySystemMaybe,
  resetHistoryBaselineOrThrow,
  resetHistoryBaselineMaybe,
  flushHistoryPendingPushMaybe,
  scheduleHistoryPushMaybe,
  pushHistoryStateMaybe,
  flushOrPushHistoryStateMaybe,
} from './history_system_access.js';

export {
  ensureRenderNamespace,
  getRenderNamespace,
  getRenderer,
  getScene,
  getCamera,
  getControls,
  getWardrobeGroup,
  getRoomGroup,
  getViewportSurface,
  getRenderSlot,
  setRenderSlot,
  getRenderCache,
  ensureRenderCacheMaps,
  readRenderCacheValue,
  writeRenderCacheValue,
  ensureRenderCacheObject,
  getRenderMeta,
  ensureRenderMetaMaps,
  getRenderMaterials,
  ensureRenderMaterialSlots,
  readRenderMaterialSlot,
  writeRenderMaterialSlot,
  ensureRenderMaterialSlot,
  bindLegacyRenderCompatRefs,
  ensureRenderCacheMap,
  ensureRenderMetaArray,
  ensureRenderMetaMap,
  getAutoLightBuildKey,
  setAutoLightBuildKey,
  getAutoCameraBuildKey,
  setAutoCameraBuildKey,
  getAmbientLight,
  setAmbientLight,
  getDirectionalLight,
  setDirectionalLight,
  ensureRenderRuntimeState,
  getShadowMap,
  getMirrorRenderTarget,
  getMirrorCubeCamera,
  getMirrorHideScratch,
  invalidateMirrorTracking,
  readAutoHideFloorCache,
  writeAutoHideFloorCache,
  readRendererCompatDefaults,
  writeRendererCompatDefaults,
  getAnimateFn,
  setAnimateFn,
  getLoopRaf,
  setLoopRaf,
  getLastFrameTs,
  setLastFrameTs,
  getRafScheduledAt,
  setRafScheduledAt,
  addToWardrobeGroup,
  addToScene,
  removeFromSceneByName,
  setRoomGroup,
  getDoorsArray,
  getDrawersArray,
  clearRenderArrays,
} from './render_access.js';

export { validateRuntimeConfig, validateRuntimeFlags } from './runtime_config_validation.js';
