import {
  ensureProjectIoRuntime,
  ensureProjectIoService,
  getProjectIoRestoreGeneration,
  getProjectIoRuntime,
  getProjectIoServiceMaybe,
  isProjectIoRestoreGenerationCurrent,
  normalizeProjectIoLoadResult,
  normalizeProjectLoadActionResultViaProjectIo,
  nextProjectIoRestoreGeneration,
} from './project_io_access_shared.js';
import {
  type ProjectExportAccessResult,
  buildDefaultProjectDataViaService,
  buildDefaultProjectDataViaServiceOrThrow,
  exportProjectResultViaService,
  exportProjectViaService,
  getProjectIoBuildDefaultProjectDataFn,
  getProjectIoHandleFileLoadFn,
  getProjectIoLoadProjectDataFn,
  handleProjectFileLoadActionResultViaService,
  handleProjectFileLoadResultViaService,
  handleProjectFileLoadViaService,
  loadProjectDataActionResultViaService,
  loadProjectDataActionResultViaServiceOrThrow,
  loadProjectDataResultViaService,
  loadProjectDataResultViaServiceOrThrow,
  loadProjectDataViaService,
  loadProjectDataViaServiceOrThrow,
  normalizeProjectExportResult,
} from './project_io_access_load.js';
import {
  type ProjectAutosavePayloadReadResult,
  type ProjectAutosavePayloadSuccessResult,
  readAutosaveProjectPayload,
  restoreProjectAutosavePayloadActionResultViaService,
  restoreProjectSessionActionResultViaService,
  restoreProjectSessionActionResultViaServiceOrThrow,
  restoreProjectSessionViaService,
} from './project_io_access_restore.js';

export type {
  ProjectExportAccessResult,
  ProjectAutosavePayloadReadResult,
  ProjectAutosavePayloadSuccessResult,
};

export {
  getProjectIoServiceMaybe,
  ensureProjectIoService,
  getProjectIoRuntime,
  ensureProjectIoRuntime,
  nextProjectIoRestoreGeneration,
  getProjectIoRestoreGeneration,
  isProjectIoRestoreGenerationCurrent,
  normalizeProjectIoLoadResult,
  normalizeProjectLoadActionResultViaProjectIo,
  exportProjectViaService,
  normalizeProjectExportResult,
  exportProjectResultViaService,
  getProjectIoHandleFileLoadFn,
  handleProjectFileLoadViaService,
  handleProjectFileLoadResultViaService,
  handleProjectFileLoadActionResultViaService,
  getProjectIoLoadProjectDataFn,
  loadProjectDataViaService,
  loadProjectDataResultViaService,
  loadProjectDataActionResultViaService,
  loadProjectDataResultViaServiceOrThrow,
  loadProjectDataActionResultViaServiceOrThrow,
  readAutosaveProjectPayload,
  restoreProjectAutosavePayloadActionResultViaService,
  restoreProjectSessionActionResultViaService,
  restoreProjectSessionActionResultViaServiceOrThrow,
  loadProjectDataViaServiceOrThrow,
  restoreProjectSessionViaService,
  getProjectIoBuildDefaultProjectDataFn,
  buildDefaultProjectDataViaService,
  buildDefaultProjectDataViaServiceOrThrow,
};
