// Runtime/base utility public API section extracted from services/api.ts

export {
  // Errors / reporting helpers
  shouldFailFast,
  reportError,
  toErrorMessage,
  getReportError,
  toError,
  guard,
  guardVoid,
  reportErrorThrottled,
  normalizeUnknownError,
  normalizeUnknownErrorInfo,
  getNormalizedErrorHead,
  normalizeErrorReason,
  buildErrorResult,
  attachErrorMessage,

  // Browser env helpers
  getBrowserDeps,
  getWindowMaybe,
  getDocumentMaybe,
  getLocationSearchMaybe,
  requestAnimationFrameMaybe,
  cancelAnimationFrameMaybe,
  requestIdleCallbackMaybe,
  getBrowserTimers,
  getBrowserFetchMaybe,
  queueMicrotaskMaybe,
  performanceNowMaybe,
  getNavigatorMaybe,
  getUserAgentMaybe,
  getBrowserMethodMaybe,
  readBrowserStringMaybe,
  triggerHrefDownloadResultViaBrowser,
  triggerHrefDownloadViaBrowser,
  triggerBlobDownloadResultViaBrowser,
  triggerBlobDownloadViaBrowser,
  triggerCanvasDownloadResultViaBrowser,
  triggerCanvasDownloadViaBrowser,
  writeClipboardTextResultViaBrowser,
  writeClipboardItemsResultViaBrowser,
  readFileTextResultViaBrowser,
  readFileDataUrlResultViaBrowser,

  // DOM helpers
  hasDom,
  get$,
  getById,
  getQs,
  getQsa,
  getHeaderLogoImageMaybe,
  getViewerContainerMaybe,
  getReactMountRootMaybe,
  ensureToastContainerMaybe,

  // Data attrs
  getDataAttrMaybe,
  getDataAttr,
  getDataAttrAny,
  hasDataAttr,
  setDataAttr,

  // DOM ops
  clearEl,
  setIconText,
  setStrongInline,
  setStrongSmall,
  getTabs,
  getTabContents,
  getScrollContainer,
  byId,

  // Runtime config validation
  validateRuntimeConfig,
  validateRuntimeFlags,

  // Assertions
  assertApp,
  assertBrowserDocument,

  // Canonical runtime seams used by UI boot
  hasStoreReactivityInstalled,
  installStoreReactivityOrThrow,
  installStoreReactivityMaybe,
  canCommitBootSeedUiSnapshot,
  commitBootSeedUiSnapshotOrThrow,
  commitBootSeedUiSnapshotMaybe,
  getHistorySystemMaybe,
  resetHistoryBaselineOrThrow,
  resetHistoryBaselineMaybe,
  flushHistoryPendingPushMaybe,
  scheduleHistoryPushMaybe,
  pushHistoryStateMaybe,
  flushOrPushHistoryStateMaybe,
  ensureRenderNamespace,
  getRenderNamespace,
  getRenderer,
  getScene,
  getCamera,
  getControls,
  getWardrobeGroup,
  getRoomGroup,
  getViewportSurface,
  getRenderSlot,
  setRenderSlot,
  getRenderCache,
  ensureRenderCacheMaps,
  readRenderCacheValue,
  writeRenderCacheValue,
  ensureRenderCacheObject,
  getRenderMeta,
  ensureRenderMetaMaps,
  getRenderMaterials,
  ensureRenderMaterialSlots,
  readRenderMaterialSlot,
  writeRenderMaterialSlot,
  ensureRenderMaterialSlot,
  bindLegacyRenderCompatRefs,
  ensureRenderCacheMap,
  ensureRenderMetaArray,
  ensureRenderMetaMap,
  getAmbientLight,
  setAmbientLight,
  getDirectionalLight,
  setDirectionalLight,
  getShadowMap,
  getMirrorRenderTarget,
  getMirrorCubeCamera,
  getMirrorHideScratch,
  invalidateMirrorTracking,
  readAutoHideFloorCache,
  writeAutoHideFloorCache,
  readRendererCompatDefaults,
  writeRendererCompatDefaults,
  getAnimateFn,
  setAnimateFn,
  getLoopRaf,
  setLoopRaf,
  getLastFrameTs,
  setLastFrameTs,
  getRafScheduledAt,
  setRafScheduledAt,
  addToWardrobeGroup,
  addToScene,
  removeFromSceneByName,
  setRoomGroup,
  getDoorsArray,
  getDrawersArray,
  clearRenderArrays,

  // Runtime perf helpers consumed by UI through the services public surface
  buildPerfEntryOptionsFromActionResult,
  markPerfPoint,
  startPerfSpan,
  endPerfSpan,
  runPerfAction,
} from '../runtime/api.js';

export { getBrowserSurfaceMaybe } from '../runtime/browser_surface_access.js';

export { asRecord } from '../runtime/record.js';

export {
  beginOwnedAsyncFamilyFlight,
  runOwnedAsyncFamilySingleFlight,
  createKeyedAsyncSingleFlightRunner,
} from '../runtime/owned_async_singleflight.js';
export type {
  OwnedAsyncFamilyFlight,
  BeginOwnedAsyncFamilyFlightResult,
} from '../runtime/owned_async_singleflight.js';
