// Actions public API section extracted from services/api.ts

export {
  getActions,
  hasAction,
  callAction,
  getActionFn,
  getActionNamespace,
  requireActionNamespace,
  getNamespacedActionFn,
  hasNamespacedAction,
  callNamespacedAction,
  listActionFns,
  ensureActionsRoot,
  ensureActionNamespace,
} from '../runtime/actions_access_core.js';

export {
  getMetaActions,
  ensureMetaActions,
  requireMetaActions,
  getMetaActionFn,
  hasMetaAction,
  callMetaAction,
  getConfigActions,
  getConfigActionFn,
  hasConfigAction,
  callConfigAction,
  getDoorsActions,
  getDoorsActionFn,
  hasDoorsAction,
  callDoorsAction,
  getModulesActions,
  getModulesActionFn,
  hasModulesAction,
  callModulesAction,
  listModulesActionFns,
  getHistoryActions,
  getHistoryActionFn,
  getModelsActions,
  getModelsActionFn,
  callModelsAction,
  getColorsActions,
  getColorsActionFn,
  callColorsAction,
  getDividersActions,
  getDividersActionFn,
  getGroovesActions,
  getGroovesActionFn,
  getRoomActions,
  getRoomActionFn,
  callRoomAction,
  getUiActions,
  getUiActionFn,
  callUiAction,
  getRuntimeActions,
  getRuntimeActionFn,
  callRuntimeAction,
  getStoreActions,
} from '../runtime/actions_access_domains.js';

export {
  setSavedNotesViaActions,
  applyProjectConfigSnapshotViaActions,
  applyProjectConfigSnapshotViaActionsOrThrow,
  applyModulesGeometrySnapshotViaActions,
  getSaveProjectAction,
  setSaveProjectAction,
  saveProjectResultViaActions,
  saveProjectViaActions,
  commitUiSnapshotViaActions,
  commitUiSnapshotViaActionsOrThrow,
  setDirtyViaActions,
  setDirtyViaActionsOrThrow,
  runHistoryBatchViaActions,
  patchViaActions,
  renderModelUiViaActions,
  renderModelUiViaActionsOrThrow,
  setMultiModeViaActions,
  applyPaintViaActions,
  toggleDividerViaActions,
  toggleGrooveViaActions,
} from '../runtime/actions_access_mutations.js';
export {
  createStructuralModulesRecomputeMeta,
  createStructuralModulesRecomputeOpts,
  didStructuralModulesRecomputeFail,
  getAppStructuralModulesRecompute,
  readStructuralModulesRecomputeResult,
  runStructuralModulesRecompute,
  runAppStructuralModulesRecompute,
} from '../runtime/modules_recompute_request_policy.js';
