// Platform/builder/render-facing service access public API section extracted from api_services_surface.ts

export {
  getPlatformBootRuntimeServiceMaybe,
  ensurePlatformBootRuntimeService,
  isPlatformBootInitDone,
  setPlatformBootInitDone,
  isPlatformBootInitRunning,
  setPlatformBootInitRunning,
} from '../runtime/platform_boot_runtime_access.js';
export {
  getPlatformRootSurface,
  ensurePlatformRootSurface,
  ensurePlatformService,
  getPlatformService,
  getPlatformUtil,
  ensurePlatformUtil,
  getBuildUIFromPlatform,
  getDimsMFromPlatform,
  ensureRenderLoopViaPlatform,
  getPlatformComputePerfFlags,
  computePerfFlagsViaPlatform,
  getPlatformSetAnimate,
  installRenderAnimateViaPlatform,
  getPlatformActivity,
  touchPlatformActivity,
  getPlatformPerf,
  getPlatformReportError,
  reportErrorViaPlatform,
  getPlatformTriggerRender,
  triggerRenderViaPlatform,
  runPlatformRenderFollowThrough,
  runPlatformWakeupFollowThrough,
  runPlatformActivityRenderTouch,
  getPlatformCreateCanvas,
  createCanvasViaPlatform,
  getPlatformLog,
  logViaPlatform,
  getPlatformStringifier,
  stringifyViaPlatform,
  getPlatformIdle,
  idleViaPlatform,
  getPlatformClone,
  cloneViaPlatform,
  getPlatformCleanGroup,
  cleanGroupViaPlatform,
  getPlatformPruneCachesSafe,
  pruneCachesViaPlatform,
  getPlatformAfterPaint,
  afterPaintViaPlatform,
  ensurePlatformHash32,
} from '../runtime/platform_access.js';
export {
  getBuilderService,
  requireBuilderService,
  getBuilderHandlesService,
  getBuilderRenderOps,
  requireBuilderRenderOps,
  getBuilderScheduler,
  getBuilderBuildUi,
  requestBuilderBuild,
  requestBuilderImmediateBuild,
  requestBuilderForcedBuild,
  requestBuilderDebouncedBuild,
  requestBuilderBuildFromActionMeta,
  requestBuilderBuildWithUiFromActionMeta,
  requestBuilderStructuralRefresh,
  refreshBuilderHandles,
  refreshBuilderAfterDoorOps,
} from '../runtime/builder_service_access.js';
export {
  ensureRoomDesignService,
  getRoomDesignServiceMaybe,
  requireRoomDesignService,
} from '../runtime/room_design_access.js';
export {
  getDoorTrimVisualsServiceMaybe,
  ensureDoorTrimVisualsService,
  ensureDoorTrimMaterialCache,
} from '../runtime/door_trim_visuals_access.js';
export {
  getBuilderDepsRoot,
  ensureBuilderDepsRoot,
  getBuilderDepsNamespace,
  ensureBuilderDepsNamespace,
  isBuilderDepsReady,
  setBuilderDepsReady,
} from '../runtime/builder_deps_access.js';
export {
  getCameraServiceMaybe,
  ensureCameraService,
  getCameraMoveHandler,
  moveCameraViaService,
} from './camera_access.js';
export { getThreeMaybe, assertThreeViaDeps } from '../runtime/three_access.js';
export {
  getSceneViewServiceMaybe,
  ensureSceneViewService,
  initSceneLightsViaService,
  installSceneViewStoreSyncViaService,
  syncSceneViewViaService,
  updateSceneLightsViaService,
  updateSceneModeViaService,
} from './scene_view_access.js';
