// Runtime/base utility public API section extracted from services/api.ts

export {
  // Errors / reporting helpers
  shouldFailFast,
  reportError,
  toErrorMessage,
  getReportError,
  toError,
  guard,
  guardVoid,
  reportErrorThrottled,
  normalizeUnknownError,
  normalizeUnknownErrorInfo,
  getNormalizedErrorHead,
  normalizeErrorReason,
  buildErrorResult,
  attachErrorMessage,

  // Browser env helpers
  getBrowserDeps,
  getWindowMaybe,
  getDocumentMaybe,
  getLocationSearchMaybe,
  requestAnimationFrameMaybe,
  cancelAnimationFrameMaybe,
  requestIdleCallbackMaybe,
  getBrowserTimers,
  getBrowserFetchMaybe,
  queueMicrotaskMaybe,
  performanceNowMaybe,
  getNavigatorMaybe,
  getUserAgentMaybe,
  getBrowserMethodMaybe,
  readBrowserStringMaybe,
  triggerHrefDownloadResultViaBrowser,
  triggerHrefDownloadViaBrowser,
  triggerBlobDownloadResultViaBrowser,
  triggerBlobDownloadViaBrowser,
  triggerCanvasDownloadResultViaBrowser,
  triggerCanvasDownloadViaBrowser,
  writeClipboardTextResultViaBrowser,
  writeClipboardItemsResultViaBrowser,
  readFileTextResultViaBrowser,
  readFileDataUrlResultViaBrowser,

  // DOM helpers
  hasDom,
  get$,
  getById,
  getQs,
  getQsa,
  getHeaderLogoImageMaybe,
  getViewerContainerMaybe,
  getReactMountRootMaybe,
  ensureToastContainerMaybe,

  // Data attrs
  getDataAttrMaybe,
  getDataAttr,
  getDataAttrAny,
  hasDataAttr,
  setDataAttr,

  // DOM ops
  clearEl,
  setIconText,
  setStrongInline,
  setStrongSmall,
  getTabs,
  getTabContents,
  getScrollContainer,
  byId,

  // Runtime config validation
  validateRuntimeConfig,
  validateRuntimeFlags,

  // Shared wardrobe dimension defaults
  DEFAULT_WIDTH,
  DEFAULT_HEIGHT,
  DEFAULT_CHEST_DRAWERS_COUNT,
  HINGED_DEFAULT_DEPTH,
  SLIDING_DEFAULT_DEPTH,
  DEFAULT_HINGED_DOORS,
  DEFAULT_SLIDING_DOORS,
  HINGED_DEFAULT_PER_DOOR_WIDTH,
  SLIDING_DEFAULT_PER_DOOR_WIDTH,
  DEFAULT_CORNER_WIDTH,
  DEFAULT_CORNER_DOORS,
  DEFAULT_STACK_SPLIT_LOWER_HEIGHT,
  STACK_SPLIT_SEAM_GAP_M,
  WARDROBE_WIDTH_MIN,
  WARDROBE_CHEST_WIDTH_MIN,
  WARDROBE_WIDTH_MAX,
  WARDROBE_HEIGHT_MIN,
  WARDROBE_CHEST_HEIGHT_MIN,
  WARDROBE_HEIGHT_MAX,
  WARDROBE_DEPTH_MIN,
  WARDROBE_DEPTH_MAX,
  WARDROBE_DOORS_MIN,
  WARDROBE_SLIDING_DOORS_MIN,
  WARDROBE_DOORS_MAX,
  WARDROBE_CHEST_DRAWERS_MIN,
  WARDROBE_CHEST_DRAWERS_MAX,
  WARDROBE_CELL_DIM_MIN,
  WARDROBE_CELL_WIDTH_MIN,
  WARDROBE_CELL_WIDTH_MAX,
  WARDROBE_CELL_HEIGHT_MIN,
  WARDROBE_CELL_HEIGHT_MAX,
  WARDROBE_CELL_DEPTH_MIN,
  WARDROBE_CELL_DEPTH_MAX,
  STACK_SPLIT_LOWER_HEIGHT_MIN,
  STACK_SPLIT_MIN_TOP_HEIGHT,
  STACK_SPLIT_LOWER_DEPTH_MIN,
  STACK_SPLIT_LOWER_DEPTH_MAX,
  STACK_SPLIT_LOWER_WIDTH_MIN,
  STACK_SPLIT_LOWER_WIDTH_MAX,
  STACK_SPLIT_LOWER_DOORS_MIN,
  STACK_SPLIT_LOWER_DOORS_MAX,
  normalizeWardrobeDimensionDefaultType,
  getDefaultDepthForWardrobeType,
  getDefaultDoorsForWardrobeType,
  getDefaultPerDoorWidthForWardrobeType,
  getDefaultWidthForWardrobeType,
  getDefaultHeightForWardrobeType,
  getDefaultChestDrawersCount,
  resolveDefaultWardrobeDimensions,

  // Assertions
  assertApp,
  assertBrowserDocument,

  // Canonical runtime seams used by UI boot
  hasStoreReactivityInstalled,
  installStoreReactivityOrThrow,
  installStoreReactivityMaybe,
  canCommitBootSeedUiSnapshot,
  commitBootSeedUiSnapshotOrThrow,
  commitBootSeedUiSnapshotMaybe,
  getHistorySystemMaybe,
  resetHistoryBaselineOrThrow,
  resetHistoryBaselineMaybe,
  flushHistoryPendingPushMaybe,
  scheduleHistoryPushMaybe,
  pushHistoryStateMaybe,
  flushOrPushHistoryStateMaybe,
  ensureRenderNamespace,
  getRenderNamespace,
  getRenderer,
  getScene,
  getCamera,
  getControls,
  getWardrobeGroup,
  getRoomGroup,
  getViewportSurface,
  getRenderSlot,
  setRenderSlot,
  getRenderCache,
  ensureRenderCacheMaps,
  readRenderCacheValue,
  writeRenderCacheValue,
  ensureRenderCacheObject,
  getRenderMeta,
  ensureRenderMetaMaps,
  getRenderMaterials,
  ensureRenderMaterialSlots,
  readRenderMaterialSlot,
  writeRenderMaterialSlot,
  ensureRenderMaterialSlot,
  bindLegacyRenderCompatRefs,
  ensureRenderCacheMap,
  ensureRenderMetaArray,
  ensureRenderMetaMap,
  getAmbientLight,
  setAmbientLight,
  getDirectionalLight,
  setDirectionalLight,
  getShadowMap,
  getMirrorRenderTarget,
  getMirrorCubeCamera,
  getMirrorHideScratch,
  invalidateMirrorTracking,
  readAutoHideFloorCache,
  writeAutoHideFloorCache,
  readRendererCompatDefaults,
  writeRendererCompatDefaults,
  getAnimateFn,
  setAnimateFn,
  getLoopRaf,
  setLoopRaf,
  getLastFrameTs,
  setLastFrameTs,
  getRafScheduledAt,
  setRafScheduledAt,
  addToWardrobeGroup,
  addToScene,
  removeFromSceneByName,
  setRoomGroup,
  getDoorsArray,
  getDrawersArray,
  clearRenderArrays,

  // Runtime perf helpers consumed by UI through the services public surface
  buildPerfEntryOptionsFromActionResult,
  markPerfPoint,
  startPerfSpan,
  endPerfSpan,
  runPerfAction,
} from '../runtime/api.js';

export type { WardrobeDimensionDefaultType } from '../runtime/api.js';

export { getBrowserSurfaceMaybe } from '../runtime/browser_surface_access.js';

export { asRecord } from '../runtime/record.js';

export {
  beginOwnedAsyncFamilyFlight,
  runOwnedAsyncFamilySingleFlight,
  createKeyedAsyncSingleFlightRunner,
} from '../runtime/owned_async_singleflight.js';
export type {
  OwnedAsyncFamilyFlight,
  BeginOwnedAsyncFamilyFlightResult,
} from '../runtime/owned_async_singleflight.js';
